### ISSUE TITLE
move to capport org

### ISSUE THREAD

**Issue by martinthomson** [wkumari/draft-ekwk-capport-rfc7710bis#14]
It should be possible for @ekline to do this.

**Comment by wkumari** [comment]
Er, what?

The draft name is 'draft-ietf-capport-rfc7710bis-00' and shows up on [https://datatracker.ietf.org/wg/capport/documents/](https://datatracker.ietf.org/wg/capport/documents/) 

The *filename* is draft-ekwk-capport-rfc7710bis, but I see no reason to change that (and lose histroy, etc).

I suspect I'm confused.

**Comment by martinthomson** [comment]
The working group maintains a GitHub organization at @capport-wg.  It would be nice, though not obligatory, for this repository to be moved under that org.

**Comment by ekline** [comment]
https://github.com/capport-wg/7710bis
