### ISSUE TITLE
add URI order of precedence section

### ISSUE THREAD

**Issue by ekline** [wkumari/draft-ekwk-capport-rfc7710bis#8]
When URIs are learned via multiple means and (heavens forbid) they differ, an order of precedence will be needed.

Suggest the following:

    [1] RA (PVD containing RA takes precedence)
    [2] (a) DHCPv6, then (b) DHCPv4
    [3] Link: relation

**Comment by ekline** [comment]
Added a section about preferring network configuration mechanisms over the link relation mechanism.

I left per-address-family provisioning precedence up to device policy for now. We can revisit this depending on the discussion in the working group.
[Simple test to see if I can edit ekline's comments...]

**Comment by wkumari** [comment]
Closed in 6911869a
